# Generated by Django 5.1.7 on 2025-04-17 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_alter_empresamodulomenu_id_empresa_modulo_and_more'),
        ('coreempresas', '0004_alter_empresaparam_id_empresa_and_more'),
        ('operadores', '0007_alter_operador_id_empresa_alter_operador_id_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadorbodega',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.RESTRICT, related_name='operador_bodegas', to='coreempresas.empresa'),
        ),
        migrations.AlterField(
            model_name='operadorbodega',
            name='id_operador',
            field=models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.RESTRICT, related_name='bodegas', to='operadores.operador'),
        ),
        migrations.AlterField(
            model_name='operadorempresamodulo',
            name='id_empresa_modulo',
            field=models.ForeignKey(db_column='id_empresa_modulo', on_delete=django.db.models.deletion.RESTRICT, related_name='operador_empresa_modulos', to='configuracion.empresamodulo'),
        ),
        migrations.AlterField(
            model_name='operadorempresamodulo',
            name='id_operador',
            field=models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.RESTRICT, related_name='operador_empresa_modulos', to='operadores.operador'),
        ),
        migrations.AlterField(
            model_name='operadorempresamodulomenu',
            name='id_empresa_modulo_menu',
            field=models.ForeignKey(db_column='id_empresa_modulo_menu', on_delete=django.db.models.deletion.RESTRICT, related_name='operador_empresa_modulos_menus', to='configuracion.empresamodulomenu'),
        ),
        migrations.AlterField(
            model_name='operadorempresamodulomenu',
            name='id_operador',
            field=models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.RESTRICT, related_name='operador_empresa_modulos_menus', to='operadores.operador'),
        ),
        migrations.AlterField(
            model_name='operadorgrupo',
            name='id_grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.RESTRICT, related_name='operadores_grupo', to='coreempresas.grupo'),
        ),
        migrations.AlterField(
            model_name='operadorgrupo',
            name='id_operador',
            field=models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.RESTRICT, related_name='operadores_grupo', to='operadores.operador'),
        ),
        migrations.AlterField(
            model_name='operadorpuntoventa',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.RESTRICT, related_name='operador_puntos_ventas', to='coreempresas.empresa'),
        ),
        migrations.AlterField(
            model_name='operadorpuntoventa',
            name='id_operador',
            field=models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.RESTRICT, related_name='operador_puntos_venta', to='operadores.operador'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.RESTRICT, to='coreempresas.empresa'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='id_operador',
            field=models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.RESTRICT, related_name='sesion', to='operadores.operador'),
        ),
        migrations.AlterField(
            model_name='sesionactiva',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.RESTRICT, to='coreempresas.empresa'),
        ),
        migrations.AlterField(
            model_name='sesionactiva',
            name='id_operador',
            field=models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.RESTRICT, related_name='sesion_activa', to='operadores.operador'),
        ),
        migrations.AlterField(
            model_name='sesionactiva',
            name='id_sesion',
            field=models.ForeignKey(db_column='id_sesion', on_delete=django.db.models.deletion.RESTRICT, related_name='sesion_activa', to='operadores.sesion'),
        ),
    ]
