# Generated by Django 5.1.7 on 2025-04-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('coreempresas', '0002_remove_empresaparam_idx_empresa_param_empresa_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresamodulo',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='empresamodulo',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='empresamodulomenu',
            name='empresa_modulo',
        ),
        migrations.RemoveField(
            model_name='empresamodulomenu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='modulo',
        ),
        migrations.AddField(
            model_name='empresamodulo',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empresa_modulos', to='coreempresas.empresa'),
        ),
        migrations.AddField(
            model_name='empresamodulo',
            name='id_modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empresa_modulos', to='configuracion.modulo'),
        ),
        migrations.AddField(
            model_name='empresamodulomenu',
            name='id_empresa_modulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='empresa_modulos_menus', to='configuracion.empresamodulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresamodulomenu',
            name='id_menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='empresa_modulos_menus', to='configuracion.menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='id_modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='menus', to='configuracion.modulo'),
        ),
        migrations.AlterField(
            model_name='empresamodulo',
            name='id',
            field=models.AutoField(db_column='id_empresa_modulo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresamodulomenu',
            name='id',
            field=models.AutoField(db_column='id_empresa_modulo_menu', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(db_column='id_menu', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='id',
            field=models.AutoField(db_column='id_modulo', primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='empresamodulo',
            index=models.Index(fields=['id_empresa'], name='idx_empresa_emm'),
        ),
        migrations.AddIndex(
            model_name='empresamodulo',
            index=models.Index(fields=['id_modulo'], name='idx_mod_emm'),
        ),
        migrations.AddIndex(
            model_name='empresamodulomenu',
            index=models.Index(fields=['id_empresa_modulo'], name='idx_emp_mod_menu'),
        ),
        migrations.AddIndex(
            model_name='empresamodulomenu',
            index=models.Index(fields=['id_menu'], name='idx_menu_emm'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['id_modulo'], name='idx_modulo_menu'),
        ),
    ]
