# Generated by Django 5.1.7 on 2025-03-28 12:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('giro', models.CharField(blank=True, max_length=255, null=True)),
                ('acteco', models.CharField(blank=True, max_length=10, null=True)),
                ('rut_firma', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.CharField(blank=True, max_length=50, null=True)),
                ('subdominio', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('fecha_incorporacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('master', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('licencias', models.IntegerField(default=5)),
                ('logo_grande', models.CharField(blank=True, max_length=255, null=True)),
                ('ingreso_pcd', models.IntegerField()),
                ('ingreso_funnel', models.IntegerField(default=0)),
                ('mercado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"dm_sistema"."empresa"',
                'indexes': [models.Index(fields=['mercado'], name='idx_empresa_mercado'), models.Index(fields=['estado'], name='idx_empresa_estado')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaResolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(default='SII', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='coreempresas.empresa')),
            ],
            options={
                'db_table': '"dm_sistema"."empresa_resolucion"',
            },
        ),
        migrations.CreateModel(
            name='EmpresaTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('FIJO', 'Fijo'), ('MOVIL', 'Móvil'), ('FAX', 'Fax'), ('OTRO', 'Otro')], max_length=10, validators=[django.core.validators.RegexValidator(regex='^(FIJO|MOVIL|FAX|OTRO)$')])),
                ('principal', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='coreempresas.empresa')),
            ],
            options={
                'db_table': '"dm_sistema"."empresa_telefono"',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('asignable', models.IntegerField(default=1)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='coreempresas.empresa')),
            ],
            options={
                'db_table': '"dm_sistema"."grupo"',
            },
        ),
        migrations.CreateModel(
            name='EmpresaParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='coreempresas.empresa')),
            ],
            options={
                'db_table': '"dm_sistema"."empresa_param"',
                'indexes': [models.Index(fields=['empresa'], name='idx_empresa_param_empresa_id'), models.Index(fields=['campo'], name='idx_empresa_param_campo')],
            },
        ),
    ]
