# Generated by Django 5.1.7 on 2025-04-17 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreempresas', '0003_remove_empresaparam_idx_empresa_param_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaparam',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.RESTRICT, related_name='parametros', to='coreempresas.empresa'),
        ),
        migrations.AlterField(
            model_name='empresaresolucion',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.RESTRICT, related_name='resoluciones', to='coreempresas.empresa'),
        ),
        migrations.AlterField(
            model_name='empresatelefono',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.RESTRICT, related_name='telefonos', to='coreempresas.empresa'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='grupos', to='coreempresas.empresa'),
        ),
    ]
