# Generated by Django 5.1.7 on 2025-04-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreempresas', '0002_remove_empresaparam_idx_empresa_param_empresa_id_and_more'),
        ('logs', '0001_initial'),
        ('operadores', '0005_remove_operador_idx_opr_emp_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='log',
            name='idx_log_cliente_id',
        ),
        migrations.RemoveIndex(
            model_name='log',
            name='idx_log_contrato_id',
        ),
        migrations.RemoveIndex(
            model_name='log',
            name='idx_log_empresa_id',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='cliente_id',
            new_name='id_cliente',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='contrato_id',
            new_name='id_contrato',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='suscriptor_id',
            new_name='id_suscriptor',
        ),
        migrations.RemoveField(
            model_name='log',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='log',
            name='operador',
        ),
        migrations.AddField(
            model_name='log',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='coreempresas.empresa'),
        ),
        migrations.AddField(
            model_name='log',
            name='id_operador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='logs', to='operadores.operador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(db_column='id_log', primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['id_cliente'], name='idx_log_idcliente'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['id_contrato'], name='idx_log_idcontrato'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['id_empresa'], name='idx_log_idemp'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['id_suscriptor'], name='idx_log_idsuscriptor'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['id_operador'], name='idx_log_idoperador'),
        ),
    ]
