# Generated by Django 5.1.7 on 2025-04-17 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreempresas', '0003_remove_empresaparam_idx_empresa_param_campo'),
        ('logs', '0002_remove_log_idx_log_cliente_id_and_more'),
        ('operadores', '0006_alter_operador_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.RESTRICT, to='coreempresas.empresa'),
        ),
        migrations.AlterField(
            model_name='log',
            name='id_operador',
            field=models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.RESTRICT, related_name='logs', to='operadores.operador'),
        ),
    ]
