# Generated by Django 5.1.7 on 2025-04-17 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_remove_empresamodulo_empresa_and_more'),
        ('coreempresas', '0003_remove_empresaparam_idx_empresa_param_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodulo',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empresa_modulos', to='coreempresas.empresa'),
        ),
        migrations.AlterField(
            model_name='empresamodulo',
            name='id_modulo',
            field=models.ForeignKey(blank=True, db_column='id_modulo', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empresa_modulos', to='configuracion.modulo'),
        ),
    ]
