# Generated by Django 5.1.7 on 2025-04-17 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_alter_empresamodulo_id_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodulomenu',
            name='id_empresa_modulo',
            field=models.ForeignKey(db_column='id_empresa_modulo', on_delete=django.db.models.deletion.RESTRICT, related_name='empresa_modulos_menus', to='configuracion.empresamodulo'),
        ),
        migrations.AlterField(
            model_name='empresamodulomenu',
            name='id_menu',
            field=models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.RESTRICT, related_name='empresa_modulos_menus', to='configuracion.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id_modulo',
            field=models.ForeignKey(blank=True, db_column='id_modulo', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='menus', to='configuracion.modulo'),
        ),
    ]
