# Generated by Django 5.1.7 on 2025-04-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreempresas', '0002_remove_empresaparam_idx_empresa_param_empresa_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='empresaparam',
            name='idx_empresa_param_campo',
        ),
    ]
