# Generated by Django 5.1.7 on 2025-03-28 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('coreempresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_id', models.CharField(max_length=50)),
                ('password', models.CharField(default='', max_length=80)),
                ('clear', models.CharField(blank=True, max_length=80, null=True)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('modificable', models.IntegerField(default=1)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('acceso_web', models.IntegerField(default=0)),
                ('conexion_fallida', models.IntegerField(default=0)),
                ('operador_administrador', models.CharField(default='0', max_length=50)),
                ('superadmin', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='coreempresas.empresa')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='coreempresas.grupo')),
            ],
            options={
                'db_table': '"dm_sistema"."operador"',
            },
        ),
        migrations.CreateModel(
            name='OperadorBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega_id', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador_bodegas', to='coreempresas.empresa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='operadores.operador')),
            ],
            options={
                'db_table': '"dm_sistema"."operador_bodega"',
            },
        ),
        migrations.CreateModel(
            name='OperadorEmpresaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.empresamodulo')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_modulos', to='operadores.operador')),
            ],
            options={
                'db_table': '"dm_sistema"."operador_empresa_modulos"',
            },
        ),
        migrations.CreateModel(
            name='OperadorEmpresaModuloMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_modulo_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.empresamodulomenu')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_modulos_menus', to='operadores.operador')),
            ],
            options={
                'db_table': '"dm_sistema"."operador_empresa_modulos_menu"',
            },
        ),
        migrations.CreateModel(
            name='OperadorGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores_grupo', to='coreempresas.grupo')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_operador', to='operadores.operador')),
            ],
            options={
                'db_table': '"dm_sistema"."operador_grupos"',
            },
        ),
        migrations.CreateModel(
            name='OperadorPuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_venta_id', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador_punto_ventas', to='coreempresas.empresa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_venta', to='operadores.operador')),
            ],
            options={
                'db_table': '"dm_sistema"."operador_punto_venta"',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField()),
                ('operador_id', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreempresas.empresa')),
            ],
            options={
                'db_table': '"dm_sistema"."sesiones"',
            },
        ),
        migrations.CreateModel(
            name='SesionActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sesion_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreempresas.empresa')),
            ],
            options={
                'db_table': '"dm_sistema"."sesiones_activas"',
            },
        ),
        migrations.CreateModel(
            name='SesionEjecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('id_ejecutivo', models.IntegerField()),
                ('rut_ejecutivo', models.CharField(blank=True, max_length=50, null=True)),
                ('id_operador', models.CharField(blank=True, max_length=50, null=True)),
                ('portal', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='coreempresas.empresa')),
            ],
            options={
                'db_table': '"dm_sistema"."sesiones_ejecutivos"',
            },
        ),
        migrations.AddIndex(
            model_name='operador',
            index=models.Index(fields=['empresa'], name='idx_opr_emp_id'),
        ),
        migrations.AddIndex(
            model_name='operador',
            index=models.Index(fields=['grupo'], name='idx_opr_grp_id'),
        ),
        migrations.AlterUniqueTogether(
            name='operador',
            unique_together={('operador_id', 'empresa')},
        ),
        migrations.AddIndex(
            model_name='operadorbodega',
            index=models.Index(fields=['bodega_id'], name='idx_opbdg_bdg_id'),
        ),
        migrations.AddIndex(
            model_name='operadorbodega',
            index=models.Index(fields=['empresa'], name='idx_opbdg_emp_id'),
        ),
        migrations.AddIndex(
            model_name='operadorempresamodulo',
            index=models.Index(fields=['operador'], name='idx_oem_opr_id'),
        ),
        migrations.AddIndex(
            model_name='operadorempresamodulo',
            index=models.Index(fields=['empresa_modulo'], name='idx_oem_em_id'),
        ),
        migrations.AddIndex(
            model_name='operadorempresamodulomenu',
            index=models.Index(fields=['operador'], name='idx_oemm_opr_id'),
        ),
        migrations.AddIndex(
            model_name='operadorempresamodulomenu',
            index=models.Index(fields=['empresa_modulo_menu'], name='idx_oemm_mm_id'),
        ),
        migrations.AlterUniqueTogether(
            name='operadorgrupo',
            unique_together={('operador', 'grupo')},
        ),
        migrations.AddIndex(
            model_name='operadorpuntoventa',
            index=models.Index(fields=['empresa'], name='idx_opv_emp_id'),
        ),
        migrations.AddIndex(
            model_name='sesionactiva',
            index=models.Index(fields=['sesion_id'], name='idx_sact_sid'),
        ),
        migrations.AddIndex(
            model_name='sesionactiva',
            index=models.Index(fields=['empresa'], name='idx_sact_emp_id'),
        ),
        migrations.AddIndex(
            model_name='sesionejecutivo',
            index=models.Index(fields=['fecha'], name='idx_seseje_fecha'),
        ),
        migrations.AddIndex(
            model_name='sesionejecutivo',
            index=models.Index(fields=['portal'], name='idx_seseje_portal'),
        ),
    ]
