# Generated by Django 5.1.7 on 2025-04-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0002_sesionactiva_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionactiva',
            name='cod_verificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
