# Generated by Django 5.1.7 on 2025-04-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0003_sesionactiva_cod_verificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SesionEjecutivo',
        ),
    ]
