# Generated by Django 5.1.7 on 2025-04-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreempresas', '0003_remove_empresaparam_idx_empresa_param_campo'),
        ('operadores', '0006_alter_operador_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.RESTRICT, related_name='operadores', to='coreempresas.empresa'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='id_grupo',
            field=models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='operadores', to='coreempresas.grupo'),
        ),
    ]
